### ISSUE TITLE
2.3.1 Update wp_get_current_user error

### ISSUE THREAD

**Issue by jsodeman** [intoxstudio/restrict-user-access#35]
Version 2.3.1 is breaking the website with the following error:

`Fatal error: Uncaught Error: Call to undefined function wp_get_current_user() in C:\Sites\thewebsite\wp-includes\capabilities.php:693 Stack trace: #0 C:\Sites\thewebsite\wp-content\plugins\ultimate-member\includes\core\class-access.php(433): current_user_can('administrator') #1 C:\Sites\thewebsite\wp-includes\class-wp-hook.php(307): um\core\Access->exclude_posts(Object(WP_Query)) #2 C:\Sites\thewebsite\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #3 C:\Sites\thewebsite\wp-includes\plugin.php(522): WP_Hook->do_action(Array) #4 C:\Sites\thewebsite\wp-includes\class-wp-query.php(1804): do_action_ref_array('pre_get_posts', Array) #5 C:\Sites\thewebsite\wp-includes\class-wp-query.php(3542): WP_Query->get_posts() #6 C:\Sites\thewebsite\wp-includes\post.php(2430): WP_Query->query(Array) #7 C:\Sites\thewebsite\wp-content\plugins\restrict-user-access\app.php(447): get_posts(Array) #8 C:\Sites\thewebsite\wp-content\plugins\restrict-user-access\app.php(594): RUA_App- in C:\Sites\thewebsite\wp-includes\capabilities.php on line 693`

From the comments on the support forum the previous version is ok
https://wordpress.org/support/topic/current-version-2-3-1-is-breaking-our-site-2-3-is-working/

**Comment by intoxstudio** [comment]
Thank you for reporting, this was fixed in v2.3.2, ff25f06ab4fcea4607e250c32e0afb409201a4b8
